#!/usr/bin/env python3
"""Generate auditable experimental Rainstorm sources from the unchanged original."""
import hashlib
import json
from pathlib import Path

HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[1]

def replace_exact(s,old,new,count):
    if s.count(old)!=count: raise RuntimeError(f'production source drift: expected {count} instances of {old!r}')
    return s.replace(old,new)

def generate():
    original=(HERE/'reference/src/rainstorm.cpp').read_text()
    source=replace_exact(original,'#include "common.h"','#include "../../../src/common.h"',1)
    variants={}
    for name in ('a','b','c','d'):
        s=replace_exact(source,'namespace rainstorm {',f'namespace rainstorm_{name} {{',1)
        if name in ('a','c'):
            s=replace_exact(s,'h[(k & 7) + 8] -= ctr;', 'h[i == 15 ? 0 : i + 1] -= ctr;',1)
        elif name=='b':
            s=replace_exact(s,'h[(k & 7) + 8] -= ctr;', 'h[(k & 7) + 8] -= (i == 15 ? (ctr << 1) : ctr);',1)
        if name in ('c','d'):
            old='''if (hashsize > 64) {
        for (int i = 0; i < std::max((int)hashsize / 64, FINAL_ROUNDS); i++) {
          weakfunc(h, temp, true);
        }
      }'''
            new='''// Experiment: four final rounds for every output size, right first.
      for (int i = 0; i < 4; i++) {
        weakfunc(h, temp, (i & 1) != 0);
      }'''
            s=replace_exact(s,old,new,1)
            old='''if (hashsize > 64) {
      for (int i = 0; i < std::max((int)hashsize / 64, FINAL_ROUNDS); i++) {
        weakfunc(h, temp, true);
      }
    }'''
            new='''// Experiment: four final rounds for every output size, right first.
    for (int i = 0; i < 4; i++) {
      weakfunc(h, temp, (i & 1) != 0);
    }'''
            s=replace_exact(s,old,new,1)
        if name=='c':
            tag=int.from_bytes(b'RNSTEXP1','little')
            helper=f'''  // One explicit 64-byte domain block: ASCII RNSTEXP1, uint64 LE
  // version=1, output bits, seed, original byte length, then three zero words.
  static inline void absorb_domain(uint64_t* h, uint64_t seed, uint64_t len, uint64_t bits) {{
    const uint64_t domain[8] = {{ UINT64_C(0x{tag:016x}), 1, bits, seed, len, 0, 0, 0 }};
    for (int i = 0; i < ROUNDS; ++i) weakfunc(h, domain, (i & 1) != 0);
  }}

'''
            s=replace_exact(s,'  struct HashState : IHashState {',helper+'  struct HashState : IHashState {',1)
            s=replace_exact(s,'      state.len = 0;', '      absorb_domain(state.h, seed, olen, hashsize);\n      state.len = 0;',1)
            s=replace_exact(s,'    uint64_t temp[8];\n    size_t lenRemaining = len;', '    absorb_domain(h, seed, len, hashsize);\n    uint64_t temp[8];\n    size_t lenRemaining = len;',1)
        header='// EXPERIMENTAL ANALYSIS VARIANT. Generated by build_variants.py.\n// Derived from src/rainstorm.cpp, Apache-2.0. Not a production replacement.\n'
        path=HERE/'variants'/f'rainstorm_{name}.cpp'
        path.write_text(header+s)
        variants[name]={'file':str(path.relative_to(ROOT)),'sha256':hashlib.sha256(path.read_bytes()).hexdigest()}
    result={'original_sha256':hashlib.sha256(original.encode()).hexdigest(),'variants':variants,
        'definitions':{'a':'Cross-half wrap; original finalization.',
            'b':'Double final right counter; original finalization.',
            'c':'A + four alternating final rounds + one explicit domain block.',
            'd':'Original round + four alternating final rounds only (optional experimental fourth).'}}
    (HERE/'variants/manifest.json').write_text(json.dumps(result,indent=2)+'\n')
    return result

if __name__=='__main__': print(json.dumps(generate(),indent=2))
